app/main/routes.py
from flask import render_template, request, Blueprint, jsonify
from flask_login import login_required

from app.main.main import *

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
    return render_template('landing/landing.html')


@main.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    countries_min = CountriesMinDataParser()
    deaths = DeathsDataParser()
    demographics = DemographicsDataParser()
    updates = UpdatesDataParser()

    countries_data = countries_min.get_countries()
    deaths_data = deaths.get_deaths()
    demographics_data = demographics.get_demographics()
    updates_data = updates.get_updates()

    return render_template('dashboard/coronavirus/dashboard.html', data=updates_data,
                           demographics=demographics_data, deaths=deaths_data, countries=countries_data)


@main.route("/news", methods=['GET', 'POST'])
@login_required
def news():
    news = NewsDataParser()
    news_data = news.get_news_updates()

    return render_template('dashboard/coronavirus/news.html', news=news_data['news'], updated=news_data['last_updated'])


@main.route("/test", methods=['GET', 'POST'])
@login_required
def test():
    return render_template('test.html')


@main.route("/api/predict/deaths", methods=['GET', 'POST'])
@login_required
def test_deaths():
    cases = start('deaths', 10, train=False)
    return jsonify(cases)


@main.route("/api/predict/cases", methods=['GET', 'POST'])
@login_required
def test_cases():
    cases = start('cases', 10, train=False)
    return jsonify(cases)


@main.route("/api/deaths", methods=['GET', 'POST'])
@login_required
def api_deaths():
    deaths = DeathsDataParser()
    return jsonify(deaths.get_deaths())


@main.route("/api/countries_min", methods=['GET', 'POST'])
@login_required
def api_countries_min():
    countries = CountriesMinDataParser()
    return jsonify(countries.get_countries())


@main.route("/api/countries_adv", methods=['GET', 'POST'])
@login_required
def api_countries_adv():
    countries = CountriesAdvDataParser()
    return jsonify(countries.get_countries())


@main.route("/api/updates", methods=['GET', 'POST'])
@login_required
def api_updates():
    updates = UpdatesDataParser()
    return jsonify(updates.get_updates())


@main.route("/api/news", methods=['GET', 'POST'])
@login_required
def api_news():
    news = NewsDataParser()
    return jsonify(news.get_news_updates())


@main.route("/api/demographics", methods=['GET', 'POST'])
@login_required
def api_demographics():
    demographics = DemographicsDataParser()
    return jsonify(demographics.get_demographics())


@main.route("/about", methods=['GET', 'POST'])
def about():
    return render_template('about.html', title='About')

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, session, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User
from app.users.forms import ( RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm )
from app.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('auth/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.dashboard'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('auth/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    session.clear()
    logout_user()
    flash("Successfuly logged out." , "primary")
    # [session.pop(key) for key in list(session.keys()) if key != '_flashes']
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('auth/account.html', title='Account',
                           image_file=image_file, form=form)



@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('auth/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('auth/reset_token.html', title='Reset Password', form=form)

app/views/main/routes.py
from flask import render_template, request, Blueprint, jsonify, send_file, current_app
from flask_login import login_required, current_user

from app.views.main.main import *

from app.views.users.routes import users

from app.utils.generate_report import generate_report

import requests
import os

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=['GET', 'POST'])
def home():
    return render_template('landing/landing.html')


@main.route("/live", methods=['GET', 'POST'])
@login_required
def monitor():

    url = 'https://media-cdn.factba.se/rss/json/coronavirus.json'

    r = requests.get(url=url)
    data = r.json()

    metrics = data['world']
    countries = sorted(data['countries'], key=lambda item: (data['countries'][item]['cases']), reverse=True)
    countries = [data['countries'][item] for item in countries if data['countries'][item]['iso3166-2']]

    cases = CasesDataParser()
    cases_data = cases.get_cases()

    return render_template('dashboard/coronavirus/monitor.html', metrics=metrics, countries=countries,
                           username=current_user.username, avatar=current_user.image_file, cases=cases_data)


@main.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    countries_adv = CountriesAdvDataParser()
    deaths = DeathsDataParser()
    demographics = DemographicsDataParser()
    updates = UpdatesDataParser()
    tests = TestsDataParser()

    countries_data = countries_adv.get_countries()
    deaths_data = deaths.get_deaths()
    demographics_data = demographics.get_demographics()
    updates_data = updates.get_updates()
    tests_data = tests.get_testing()
    print(tests_data)

    return render_template('dashboard/coronavirus/dashboard.html', data=updates_data, username=current_user.username,
                           avatar=current_user.image_file, demographics=demographics_data, deaths=deaths_data,
                           countries=countries_data, tests=tests_data)


@main.route("/news", methods=['GET', 'POST'])
@login_required
def news():
    news = NewsDataParser()
    news_data = news.get_news_updates()

    return render_template('dashboard/coronavirus/news.html', news=news_data['news'], updated=news_data['last_updated'], 
                            username=current_user.username, avatar=current_user.image_file,)


@main.route("/countries", methods=['GET', 'POST'])
@login_required
def countries():
    countries = CountriesAdvDataParser()
    countries_data = countries.get_countries()

    return render_template('dashboard/coronavirus/countries.html', countries=countries_data, username=current_user.username,
                           avatar=current_user.image_file,)


@main.route("/countries/<string:country>", methods=['GET', 'POST'])
@login_required
def single_country(country):
    country_data = SingleCountryParser()
    data = country_data.get_country_data(country)

    population_data = {
        "China": { 'population': '1,439,323,776', 'density': 153, 'land': '9,388,211' },
        "South Korea": { 'population': '51,269,185', 'density': 527, 'land': '97,230' },
        "United States": { 'population': '331,002,651', 'density': 36, 'land': '9,147,420' },
        "United Kingdom": { 'population': '67,886,011', 'density': 281, 'land': '241,930' },
        "Iran": { 'population': '83,992,949', 'density': 52, 'land': '1,628,550' },
        "Italy": { 'population': '60,461,826', 'density': 206, 'land': '294,140' },
        "France": { 'population': '65,273,511', 'density': 119, 'land': '547,557' },
        "Spain": { 'population': '46,754,778', 'density': 94, 'land': '498,800' },
        "Germany": { 'population': '83,783,942', 'density': 153, 'land': '348,560' },
        "Canada": { 'population': '37,742,154', 'density': 4, 'land': '9,093,510' },
        "Australia": { 'population': '25,499,884', 'density': 3, 'land': '7,682,300' },
        "Switzerland": { 'population': '8,654,622', 'density': 219, 'land': '39,516' },

    }

    return render_template('dashboard/coronavirus/country.html', data=data, population=population_data,
                           username=current_user.username, avatar=current_user.image_file)

@main.route('/history')
@login_required
def history():
    return render_template('dashboard/coronavirus/history.html', username=current_user.username, avatar=current_user.image_file,)


@main.route("/predictions", methods=['GET', 'POST'])
@login_required
def predictions():
    deaths_predicted = start('deaths', 10, train=False)
    cases_predicted = start('cases', 10, train=False)

    stats = MainStatsDataParser()
    stats_data = stats.get_stats()

    cases = { "cases_data": list(zip(DataParser.create_date_axis_forward(cases_predicted), cases_predicted)) }
    deaths = { "deaths_data": list(zip(DataParser.create_date_axis_forward(deaths_predicted), deaths_predicted)) }

    return render_template('dashboard/coronavirus/predictions.html', deaths=deaths,
                           cases=cases, stats=stats_data,
                           username=current_user.username, avatar=current_user.image_file,)


@main.route("/documentation", methods=['GET', 'POST'])
def docs():
    return render_template('docs.html', title='Docs')


@main.route('/download_report')
def download_report():

    directory = os.path.join(
        os.path.dirname(current_app.instance_path), f'app/userdata/{current_user.username}/reports'
    )

    if not os.path.exists(directory):
        os.makedirs(directory)

    stats = MainStatsDataParser()
    stats_data = stats.get_stats()
    demographics = DemographicsDataParser()
    demographics_data = demographics.get_demographics()
    countries = CountriesAdvDataParser()
    countries_data = countries.get_countries()

    data = {
        "countries": countries_data,
        "statistics": stats_data,
        "demographics": demographics_data
    }

    url = generate_report(current_user.username, data)

    return send_file(url, as_attachment=False, cache_timeout=0)


@main.route("/api/predict/deaths", methods=['GET', 'POST'])
@login_required
def test_deaths():
    cases = start('deaths', 10, train=True)
    return jsonify(cases)


@main.route("/api/predict/cases", methods=['GET', 'POST'])
@login_required
def test_cases():
    cases = start('cases', 10, train=True)
    return jsonify(cases)


@main.route('/api/csse/data')
def csse_data():
    confirmed = get_data('confirmed')
    deaths    = get_data('deaths')
    recovered = get_data('recovered')

    return jsonify({
        'confirmed': confirmed,
        'deaths':    deaths,
        'recovered': recovered,
    })


@main.route("/api/deaths", methods=['GET', 'POST'])
@login_required
def api_deaths():
    deaths = DeathsDataParser()
    return jsonify(deaths.get_deaths())


@main.route("/api/countries_min", methods=['GET', 'POST'])
@login_required
def api_countries_min():
    countries = CountriesMinDataParser()
    return jsonify(countries.get_countries())


@main.route("/api/countries_adv", methods=['GET', 'POST'])
@login_required
def api_countries_adv():
    countries = CountriesAdvDataParser()
    return jsonify(countries.get_countries())


@main.route("/api/updates", methods=['GET', 'POST'])
@login_required
def api_updates():
    updates = UpdatesDataParser()
    return jsonify(updates.get_updates())


@main.route("/api/news", methods=['GET', 'POST'])
@login_required
def api_news():
    news = NewsDataParser()
    return jsonify(news.get_news_updates())


@main.route("/api/demographics", methods=['GET', 'POST'])
@login_required
def api_demographics():
    demographics = DemographicsDataParser()
    return jsonify(demographics.get_demographics())


@main.route("/api/cases", methods=['GET', 'POST'])
@login_required
def api_cases():
    cases = CasesDataParser()
    return jsonify(cases.get_cases())


@main.route("/api/tests", methods=['GET', 'POST'])
@login_required
def api_tests():
    tests = TestsDataParser()
    return jsonify(tests.get_testing())


@main.route("/api/countries/<string:country>", methods=['GET', 'POST'])
@login_required
def api_single_country(country):
    country_data = SingleCountryParser()
    return jsonify(country_data.get_country_data(country))

app/templates/dashboard/coronavirus/includes/_navbar.html
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">
        <div class="navbar-logo">
            <a class="mobile-menu" id="mobile-collapse" href="#!">
                <i class="feather icon-menu"></i>
            </a>
            <a href="{{ url_for('main.home')}}">
                <img class="img-fluid" src="{{ url_for('static', filename='images/logo_covid.png')}}" alt="Theme-Logo">
            </a>
            <a class="mobile-options">
                <i class="feather icon-more-horizontal"></i>
            </a>
        </div>
        <div class="navbar-container container-fluid">
            <ul class="nav-left">
                <li>
                    <a href="#!" onclick="javascript:toggleFullScreen()">
                        <i class="feather icon-maximize full-screen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                <li class="user-profile header-notification">
                    <div class="dropdown-primary dropdown">
                        <div class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ avatar }}" class="img-radius" alt="User-Profile-Image">
                            <span>{{username}}</span>
                            <i class="feather icon-chevron-down"></i>
                        </div>
                        <ul class="show-notification profile-notification dropdown-menu" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
                            <li>
                                <a href="#!">
                                    <i class="feather icon-settings"></i> Report a Bug
                                </a>
                            </li>
                            <li>
                                <a href="{{url_for('users.profile')}}">
                                    <i class="feather icon-user"></i> Profile
                                </a>
                            </li>
                            <li>
                                <a href="{{url_for('users.logout')}}">
                                    <i class="feather icon-log-out"></i> Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/templates/dashboard/coronavirus/includes/_sidebar.html
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel">Navigation</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu active pcoded-trigger">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-home"></i></span>
                    <span class="pcoded-mtext">Dashboard</span>
                </a>
                <ul class="pcoded-submenu">
                    <li class="">
                        <a href="{{ url_for('main.monitor')}}">
                            <span class="pcoded-mtext">Live Monitor</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('main.dashboard')}}">
                            <span class="pcoded-mtext">Coronavirus Data</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('main.history')}}">
                            <span class="pcoded-mtext">History (JHU CSSE)</span>
                        </a>
                    </li>
                    <li class="pcoded-hasmenu">
                        <a href="javascript:void(0)">
                            <span class="pcoded-micon"><i class="feather icon-cpu"></i></span>
                            <span class="pcoded-mtext">Countires</span>
                            <span class="pcoded-badge label label-danger">NEW</span>
                        </a>
                        <ul class="pcoded-submenu">
                            <li class="">
                                <a href="{{ url_for('main.countries')}}">
                                    <span class="pcoded-mtext">Countries</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='china')}}">
                                    <span class="pcoded-mtext">China</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='italy')}}">
                                    <span class="pcoded-mtext">Italy</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='us')}}">
                                    <span class="pcoded-mtext">United States</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='uk')}}">
                                    <span class="pcoded-mtext">United Kingdom</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='south-korea')}}">
                                    <span class="pcoded-mtext">South Korea</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='spain')}}">
                                    <span class="pcoded-mtext">Spain</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='france')}}">
                                    <span class="pcoded-mtext">France</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='germany')}}">
                                    <span class="pcoded-mtext">Germany</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='iran')}}">
                                    <span class="pcoded-mtext">Iran</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='canada')}}">
                                    <span class="pcoded-mtext">Canada</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='australia')}}">
                                    <span class="pcoded-mtext">Australia</span>
                                </a>
                            </li>
                            <li class="">
                                <a href="{{ url_for('main.single_country', country='switzerland')}}">
                                    <span class="pcoded-mtext">Switzerland</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="">
                        <a href="{{ url_for('main.predictions')}}">
                            <span class="pcoded-micon"><i class="feather icon-cpu"></i></span>
                            <span class="pcoded-mtext">Predictions</span>
                            <span class="pcoded-badge label label-danger">NEW</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('main.news')}}">
                            <span class="pcoded-micon"><i class="feather icon-cpu"></i></span>
                            <span class="pcoded-mtext">News</span>
                            <span class="pcoded-badge label label-danger">NEW</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('main.download_report')}}">
                            <span class="pcoded-micon"><i class="feather icon-cpu"></i></span>
                            <span class="pcoded-mtext">Download Report</span>
                            <span class="pcoded-badge label label-danger">NEW</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="pcoded-navigatio-lavel">Economics</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="feather icon-box"></i></span>
                    <span class="pcoded-mtext">Markets</span>
                    <span class="pcoded-badge label label-warning">SOON</span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="">
                            <span class="pcoded-mtext">Stock Market</span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="">
                            <span class="pcoded-mtext">USA Market</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="pcoded-navigatio-lavel">Miscellaneous</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="">
                <a href="{{url_for('main.docs')}}" target="_blank">
                    <span class="pcoded-micon"><i class="feather icon-monitor"></i></span>
                    <span class="pcoded-mtext">Documentation</span>
                </a>
            </li>
            <li class="">
                <a href="#" target="_blank">
                    <span class="pcoded-micon"><i class="feather icon-help-circle"></i></span>
                    <span class="pcoded-mtext">Submit an Issue</span>
                </a>
            </li>
        </ul>
    </div>
</nav>